languageCode = "ko-KR"
defaultContentLanguage = "ko" # "en"
enableRobotsTXT = true
enableEmoji = true

theme = "simple-cv"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

baseURL = "https://example.com/"
title = "함경재 포트폴리오"
favicon = "/img/xLzaaP9J.ico"
#googleAnalytics = ""

[params]
enableMetaTags = true
colorLight = "#fff"
colorDark = "#666"
colorPageBackground = "#ddd"
colorPrimary = "#dbdbdb"
colorIconPrimary = "#ccc"
colorIconSecondary = "#e3bfb8"
colorIconBackground = "#dbdbdb"
colorLeftColumnBackground = "#333"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
pages = 1
